In [77]:
import torch
from torch import nn
import torch.nn.utils.rnn as rnn_utils
from torch.utils.data import DataLoader
import torch.utils.data as data

train_x = [torch.Tensor([[1, 1], [1, 1], [1, 1], [1,1]]),
           torch.Tensor([[2, 2], [2, 2], [2, 2]]),
           torch.Tensor([[3, 3], [3, 3]]),
           torch.Tensor([[4, 4], [4, 4]]),
           torch.Tensor([[5, 5]]),
           torch.Tensor([[6,6]])
        ]
print(train_x)

[tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]), tensor([[2., 2.],
        [2., 2.],
        [2., 2.]]), tensor([[3., 3.],
        [3., 3.]]), tensor([[4., 4.],
        [4., 4.]]), tensor([[5., 5.]]), tensor([[6., 6.]])]


In [78]:
class MyData(data.Dataset):
    def __init__(self, data_seq):
        self.data_seq = data_seq

    def __len__(self):
        return len(self.data_seq)

    def __getitem__(self, idx):
        return self.data_seq[idx]
    
def collate_fn(data):
    data.sort(key=lambda x: len(x), reverse=True)
    data_length = [len(sq) for sq in data]
    data = rnn_utils.pad_sequence(data, batch_first=True, padding_value=0)
    return data, data_length

batch_size=2
if __name__=='__main__':
    data = MyData(train_x)
    data_loader = DataLoader(data, batch_size=batch_size, shuffle=True, 
                             collate_fn=collate_fn)
    batch_x, batch_x_len = iter(data_loader).next()
    batch_x_pack = rnn_utils.pack_padded_sequence(batch_x, 
                                                  batch_x_len, batch_first=True)
print(batch_x,batch_x_len)
print(batch_x_pack)

tensor([[[2., 2.],
         [2., 2.],
         [2., 2.]],

        [[4., 4.],
         [4., 4.],
         [0., 0.]]]) [3, 2]
PackedSequence(data=tensor([[2., 2.],
        [4., 4.],
        [2., 2.],
        [4., 4.],
        [2., 2.]]), batch_sizes=tensor([2, 2, 1]))


In [191]:
def pack(data):
    data = MyData(data)
    data_loader = DataLoader(data, batch_size=batch_size, shuffle=True, 
                             collate_fn=collate_fn)
    batch_x, batch_x_len = iter(data_loader).next()
    batch_x_pack = rnn_utils.pack_padded_sequence(batch_x, 
                                                  batch_x_len, batch_first=True)
    return batch_x_pack

In [125]:
#RNN
num_layers=1
input_size=2
output_size=2

net = nn.RNN(input_size, output_size, num_layers)#输入维度2，输出维度3
h0 = torch.rand(num_layers, batch_size, output_size)
#print(batch_x_pack.data.shape)#
out, (h1) = net(batch_x_pack,h0)
#print(out.data.shape)#
print(h1)#

tensor([[[-0.6722, -0.5852],
         [-0.9685, -0.6535]]], grad_fn=<StackBackward>)


In [126]:
#Linear
Linear=nn.Linear(input_size,output_size)
output=Linear(batch_x_pack.data)
print(output)

tensor([[-0.4714, -2.5254],
        [-1.0795, -4.8525],
        [-0.4714, -2.5254],
        [-1.0795, -4.8525],
        [-0.4714, -2.5254]], grad_fn=<AddmmBackward>)


In [129]:
h0 = torch.rand(1, 2, 2)#batch_first=False
net(output.data[0:2].reshape(1,2,-1),h0)

(tensor([[[ 0.6763, -0.9380],
          [ 0.9015, -0.9831]]], grad_fn=<StackBackward>),
 tensor([[[ 0.6763, -0.9380],
          [ 0.9015, -0.9831]]], grad_fn=<StackBackward>))

In [145]:
#X与h的shape对齐。
h_size=h0.shape[1]
xdata=output.data[0:2].reshape(1,2,-1)
print(h_size)
x_size=xdata.shape[1]
print(x_size)
if (h_size<x_size):
    xdata=xdata[:,0:h_size,:]
print(xdata)

2
2
tensor([[[-0.4714, -2.5254],
         [-1.0795, -4.8525]]])


In [220]:
#for循环获取h的batch
length=0
xdatas=[]
for index in range(len(batch_x_pack.batch_sizes)-1):
    h_batch_size=batch_x_pack.batch_sizes[index]
    print(h_batch_size)
    if(len(xdatas)==2):
        del xdatas[0]
    out=output.data[length:length+h_batch_size].reshape(1,h_batch_size,-1)
    length=length+h_batch_size
    h_size=batch_x_pack.batch_sizes[index+1]
    h= batch_x_pack.data[length:length+h_size].reshape(1,h_size,-1)
    print(h)
    
    #size 调整
    print(h_size)
    xdatas.append(out[:,0:h_size,:])
    xdatas[0]=xdatas[0][:,0:h_size,:]
    print(xdatas)
    
    #pack
    train_h=xdatas
    print('train_h')
    print(train_h)
    if(len(xdatas)==2):
        train_h=torch.stack((xdatas[0],xdatas[1]),dim=1).reshape(2,h_size,-1)
    else:
        train_h=xdatas[0]
    print(train_h)
    #Net
    out,h1=net(train_h,h)
    print('out')
    print(out)
    print(h1)

tensor(2)
tensor([[[2., 2.],
         [4., 4.]]])
tensor(2)
[tensor([[[-0.4714, -2.5254],
         [-1.0795, -4.8525]]])]
train_h
[tensor([[[-0.4714, -2.5254],
         [-1.0795, -4.8525]]])]
tensor([[[-0.4714, -2.5254],
         [-1.0795, -4.8525]]])
out
tensor([[[ 0.5030, -0.8436],
         [ 0.7255, -0.9101]]], grad_fn=<StackBackward>)
tensor([[[ 0.5030, -0.8436],
         [ 0.7255, -0.9101]]], grad_fn=<StackBackward>)
tensor(2)
tensor([[[2., 2.]]])
tensor(1)
[tensor([[[-0.4714, -2.5254]]]), tensor([[[-0.4714, -2.5254]]])]
train_h
[tensor([[[-0.4714, -2.5254]]]), tensor([[[-0.4714, -2.5254]]])]
tensor([[[-0.4714, -2.5254]],

        [[-0.4714, -2.5254]]])
out
tensor([[[ 0.5030, -0.8436]],

        [[ 0.7784, -0.8047]]], grad_fn=<StackBackward>)
tensor([[[ 0.7784, -0.8047]]], grad_fn=<StackBackward>)


In [173]:
for h_batch_size in range(len(batch_x_pack.batch_sizes)):
    print(h_batch_size)

0
1
2
